### ISSUE TITLE
Integrating binder/thebe with documentation?

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/preliz#10]
I there isn't much to win from static docs or notebooks in preliz, but we can write some "ready to run" notebooks that can be executed with binder or thebe (which would be even better I think). 

With thebe for example, the docs themseves have a button to run the code without even leaving the website (and it runs binder behind the scenes and interfaces with the docs website). We used that for example in the [pymc sprint](https://pymc-data-umbrella.xyz/en/latest/webinars/intro_to_array_operations/notebook.html), however, binder doesn't offer a lot of computing power, so it's use for pymc it's limited due to slowness and lack of available RAM, but hopefully with preliz things would work fast enough to show interactiveness.

**Comment by aloctavodia** [comment]
this will be fantastic!

**Comment by OriolAbril** [comment]
addressed in https://github.com/arviz-devs/preliz/pull/13

**Comment by aloctavodia** [comment]
The example is not working due to a scikit-learn installation issue.
