### ISSUE TITLE
Automatically render the output of ipywidgets 

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/preliz#183]
Currently, we need to 

1. Click on "delete widget state".
2. Restart the notebook
3. Click on  "save widget state".

Here there are other alternatives  that we could implement https://ipywidgets.readthedocs.io/en/8.0.2/embedding.html

Using nbsphinx is not a solution as stated in #177 by @OriolAbril

**Comment by OriolAbril** [comment]
I have only been able to skim it very roughly. I think the main issue is that for the widget to actually work, it needs a python kernel, not only loading the right javascript. I think [this page from myst-nb](https://myst-nb.readthedocs.io/en/v0.16.0/render/interactive.html#ipywidgets) explains the reason quite well.

Therefore, I think it will be possible to render the widget, but probably not to allow users to properly interact with it online.

**Comment by aloctavodia** [comment]
This works as intended in Jupyter 7.0.6, probably it has been solved in 7.0 as I see many changes in Jupyter notebook interface and widgets options.
