### ISSUE TITLE
Add plot_interactive method to Dirichlet and MvNormal

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/preliz#225]

**Comment by rohanbabbar04** [comment]
Hi @aloctavodia ,
If this issue is still open, would like to work on it

**Comment by aloctavodia** [comment]
Hi @rohanbabbar04, yes this is still unsolved. You can go ahead. Thanks!

**Comment by rohanbabbar04** [comment]
Now coming back to this issue, What would you recommend on the widget to be used in this case..
Since Dirichlet has alpha as a parameter `alpha=[1, 2, ....]`. And I think we should be able to modify it...
Dirichlet plots betas of each alpha[i] parameter.

Would you go for a slider for each subplot which controls the alpha of each beta plot, or a rectangle box showing all the alphas, or something else??

**Comment by aloctavodia** [comment]
We need to use sliders to be consistent with how `plot_interactive()` works for 1D distributions. 

As a side comment:

One downside of sliders is that max and min boundaries are fixed (at least for the default sliders). That's why for `predictive_explorer()` we use boxes.

Why do we use boxes in one case and sliders in the other? Because I think `plot_interactive` is more about gaining intuition into how parameters affect a given distribution. Thus having a "reasonable" range of values to play with, should be enough in most cases. Instead `predictive_explorer()` requires more "fine-tuning", and thus boxes are better. But of course, this is very opinionated. Others may want to use these functions in other ways.

**Comment by rohanbabbar04** [comment]
Ok..

So we create a slider for each subplot right?

**Comment by aloctavodia** [comment]
Yes for arbitrary dimensions. For dim=3 a join plot should also be an option

**Comment by rohanbabbar04** [comment]
For sliders,
I am a little confused about which widgets would suit this problem(and make it aesthetically look good)

I thought about a Selection box allowing users the alpha(conc parameter to alter) and a slider for each selection
Like this ⬇️ (I don't know if this is the best, @aloctavodia what do you suggest??)
![image](https://github.com/arviz-devs/preliz/assets/77425744/cc2f6398-f4a9-482f-ab06-07afe628001e)


I also thought about putting a slider above each subplot, but it may pose problems for `join plot`, also for larger values it doesn't look good...

**Comment by rohanbabbar04** [comment]
So the above implementation wherein you have a select box to select the dim in `alpha=[1,2,3,4...]`
And can use the slider to change that value in the list

Do you think it serves our purpose?

**Comment by aloctavodia** [comment]
Just one slider per dimension, one below the other. No box.
