### ISSUE TITLE
Interactive examples are not able to show the widgets

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/preliz#229]
This is the error when trying to run `pz.roulette()` from https://preliz.readthedocs.io/en/latest/examples/param_space_1d_examples.html

[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'MPLCanvasModel' from module 'jupyter-matplotlib'
makeError@https://hub.gke2.mybinder.org/user/arviz-devs-arviz_sandbox-pyp8w7j3/static/nbclassic/components/requirejs/require.js?v=d37b48bb2137faa0ab98157e240c084dd5b1b5e74911723aa1d1f04c928c2a03dedf922d049e4815f7e5a369faa2e6b6a1000aae958b7953b5cc60411154f593:168:17
checkLoaded@https://hub.gke2.mybinder.org/user/arviz-devs-arviz_sandbox-pyp8w7j3/static/nbclassic/components/requirejs/require.js?v=d37b48bb2137faa0ab98157e240c084dd5b1b5e74911723aa1d1f04c928c2a03dedf922d049e4815f7e5a369faa2e6b6a1000aae958b7953b5cc60411154f593:696:23
newContext/checkLoaded/checkLoadedTimeoutId<@https://hub.gke2.mybinder.org/user/arviz-devs-arviz_sandbox-pyp8w7j3/static/nbclassic/components/requirejs/require.js?v=d37b48bb2137faa0ab98157e240c084dd5b1b5e74911723aa1d1f04c928c2a03dedf922d049e4815f7e5a369faa2e6b6a1000aae958b7953b5cc60411154f593:717:25

**Comment by OriolAbril** [comment]
I looked around a little bit and have no idea what is going on, it does work on binder, not when using thebe to execute things wihtin the website. How would you feel about making binder much more prominent and dropping thebe which is giving more headaches than anything?

**Comment by aloctavodia** [comment]
Not sure what to do, Thebe functionality is very nice, and this should be working according to this https://github.com/executablebooks/thebe/pull/418. But not opposed to dropping thebe in favor of binder

**Comment by aloctavodia** [comment]
The error message is:

Uncaught (in promise) Error: Module @jupyter-widgets/controls, semver range ^2.0.0 is not registered as a widget module

This may be due to an incompatibility with ipywidgets 8.x
