### ISSUE TITLE
Support Matplotlib>=3.8.0

### ISSUE THREAD

**Issue by hectormz** [arviz-devs/preliz#284]
## Tell us about it

`preliz` requires matplotlib <= 3.8.0 according to the `pyproject.toml`. After running tests myself, it looks like this in part related to the fact that [The iterator ''prop_cycler'' is removed from ax._get_lines after v3.8.0](https://github.com/matplotlib/matplotlib/issues/26831)

This is used in `prop_helper.py` in three places:

https://github.com/arviz-devs/preliz/blob/3e09a384d538b427f367aa18639b7cf9c5a1e09c/preliz/internal/plot_helper.py#L112

This is an internal, undocumented behavior in `matplotlib`, so it might make sense to move on from it. Am I correct in assuming that this exists to get the next color in the color cycle to plot?

**Comment by aloctavodia** [comment]
Thanks for opening this issue. It has been fixed now.

**Comment by hectormz** [comment]
Thanks @aloctavodia !
