### ISSUE TITLE
Tkinter not working with Thebe/Binder

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/preliz#32]
Maybe we can make it work by doing 

```python
from xvfbwrapper import Xvfb

with Xvfb() as xvfb:
    pz.roulette()
```

or 

```python
import pyvirtualdisplay

_display = pyvirtualdisplay.Display(visible=False,  # use False with Xvfb
                                    size=(1400, 900))
_ = _display.start()
```

Both approaches require to have `xvfb` and maybe also `x11-utils`, which are not installed by default. I try to install them by adding a apt.txt file to the root of the repo. But it seems binder is not installing it.

**Comment by OriolAbril** [comment]
The binder image is generated from https://github.com/arviz-devs/arviz_sandbox so the `apt.txt` should be added there (as well as the python wrappers in requirements.txt)

**Comment by aloctavodia** [comment]
ohh thanks!

**Comment by aloctavodia** [comment]
OK, Now everything is installed. But still tkinter is not working. It seems the window pop-ups but is not visible :-(

**Comment by aloctavodia** [comment]
More than a restriction on the binder side, I think is a limitation jupyter notebooks. 

At this point I think that to make this work it would require to write a jupyter extension, here I found some possible routes 
https://stackoverflow.com/questions/19556947/html5-javascript-x11-server.
