### ISSUE TITLE
Add test beta_mode

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/preliz#320]
see #309 for details

**Comment by nishant42491** [comment]
I have opened a pr #323 for this can you have a look?

**Comment by aloctavodia** [comment]
Thank  you. Don't need to directly notify me when doing a PR or opening and issue. I get emails notifications. Also when open a PR related to an issue you can use these magic words https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
