### ISSUE TITLE
Implement more efficient distributions

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/preliz#345]
We should focus on the ones marked with ** first

* [x] AsymmetricLaplace **
* [x] Beta **
* [x] BetaScaled
* [x] Cauchy
* [x] ChiSquared
* [x] ExGaussian
* [x] Exponential ** 
* [x] Gamma ** 
* [x] Gumbel
* [x] HalfCauchy
* [x] HalfNormal ** 
* [x] HalfStudentT ** 
* [x] InverseGamma
* [x] Kumaraswamy
* [x] Laplace ** 
* [x] LogNormal
* [x] Logistic
* [x] LogitNormal
* [x] Moyal
* [x] Normal ** 
* [x] Pareto
* [x] Rice
* [x] SkewNormal
* [x] StudentT ** 
* [x] Triangular
* [x] TruncatedNormal
* [x]  Uniform
* [x] VonMises **
* [x] Wald **
* [x] Weibull ** 
* [x] Bernoulli **
* [x] BetaBinomial
* [x] Binomial **
* [x]  Categorical ** 
* [x] DiscreteUniform
* [x] DiscreteWeibull
* [x] Geometric
* [x] HyperGeometric
* [x] NegativeBinomial **
* [x] Poisson **
* [x] ZeroInflatedBinomial **
* [x] ZeroInflatedNegativeBinomial **
* [x] ZeroInflatedPoisson **

**Comment by rohanbabbar04** [comment]
Let me also take some of the Distributions...
I'll start with Exponential

**Comment by rohanbabbar04** [comment]
I'll take `Laplace` and `AssymmetricLaplace` next

**Comment by rohanbabbar04** [comment]
> I'll take `Laplace` and `AssymmetricLaplace` next

Any suggestion on how to implement the `rvs` of `AsymmetricLaplace`?

**Comment by aloctavodia** [comment]
You can sample from a uniform distribution and then apply a transformation see https://en.m.wikipedia.org/wiki/Asymmetric_Laplace_distribution#Generating_asymmetric_Laplace_variates

**Comment by rohanbabbar04** [comment]
> I'll take `Laplace` and `AssymmetricLaplace` next

After this I will take `Gamma`

**Comment by rohanbabbar04** [comment]
I'll take Triangular next

**Comment by rohanbabbar04** [comment]
I'll take `Logistic` and `Pareto` next

**Comment by rohanbabbar04** [comment]
I'll take Cauchy next...

**Comment by rohanbabbar04** [comment]
I'll take HalfCauchy next...

**Comment by rohanbabbar04** [comment]
'll take TruncatedNormal next...
