### ISSUE TITLE
Add tests for PyMC functionality

### ISSUE THREAD

**Issue by ricardoV94** [arviz-devs/preliz#433]
I think the PyMC code can be quite simplified, but without a test suite I wouldn't venture refactoring it :)

**Comment by aloctavodia** [comment]
@rohanbabbar04 can you work on this? You can use the notebook I shared with you as a starting point. To add context @ricardoV94 is a PyMC expert, so his help will be very valuable.

**Comment by rohanbabbar04** [comment]
Sure, I will look into this and add tests...
