### ISSUE TITLE
Improve presentation of distributions on the PreliZ page

### ISSUE THREAD

**Issue by aleicazatti** [arviz-devs/preliz#448]
## Tell us about it

The current presentation of distributions on the PreliZ API page is too verbose, which is suitable for technical details but not very user-friendly. 

## Thoughts on implementation

**1. Create a distributions grid page:**

- Develop a new page with a grid of images (like [ArviZ example gallery](https://python.arviz.org/en/stable/examples/index.html)), each representing a distribution's probability density function (PDF).

- Clicking on an image should lead to more detailed information, including the "story" or history of the distribution.

**2. Detailed individual pages for each distribution:**

- Simplify the information by distilling content from sources like Wikipedia, making it more accessible.

- Include concise, "Bayesian-focused" stories for each distribution.

- Provide visual examples, parameter explanations, and common uses.

- Implement "See also" sections to link related distributions.

- Add tags for easier searching based on domain, parameters, symmetry, etc.

**Comment by aloctavodia** [comment]
We should also create specific issues for each distribution, that will help us distribute the work and we could use the specific issues to collect and discuss the specific information we want to add to each element in the grid. 

For the See Also, we could use this as a guide https://upload.wikimedia.org/wikipedia/commons/a/af/ProbOnto2.5.jpg, after a quick look I think a good principle could be to add a "See also" if two distributions are first neighbours in this graph. We could consider other cases too, for instance it makes sense that NegativeBinomial and ZINB should have mutual "see also" links.  And also we should consider simplifications, for instance merge Normal with StandardNormal, or StudentT 1, 2 and 3 together with NoncentralT1. Still it could be a good guide.

Other sources for stories or useful information can be https://distribution-explorer.github.io/discrete/bernoulli.html and https://www.acsu.buffalo.edu/~adamcunn/probability/betabinomial.html

**Comment by aleicazatti** [comment]
Progress tracker for individual distribution pages:

* [ ] [AsymmetricLaplace](#449 )
* [ ] Beta
* [ ] BetaScaled
* [ ] Cauchy
* [ ] ChiSquared
* [ ] ExGaussian
* [ ] Exponential
* [ ] Gamma
* [ ] Gumbel
* [ ] HalfCauchy
* [ ] HalfNormal
* [ ] HalfStudentT
* [ ] InverseGamma
* [ ] Kumaraswamy
* [ ] Laplace
* [ ] LogNormal
* [ ] Logistic
* [ ] LogitNormal
* [ ] Moyal
* [ ] Normal
* [ ] Pareto
* [ ] Rice
* [ ] SkewNormal
* [ ] StudentT
* [ ] Triangular
* [ ] TruncatedNormal
* [ ] Uniform
* [ ] VonMises
* [ ] Wald
* [ ] Weibull
* [ ] Bernoulli
* [ ] BetaBinomial
* [ ] Binomial
* [ ] Categorical
* [ ] DiscreteUniform
* [ ] DiscreteWeibull
* [ ] Geometric
* [ ] HyperGeometric
* [ ] NegativeBinomial
* [ ] Poisson
* [ ] ZeroInflatedBinomial
* [ ] ZeroInflatedNegativeBinomial
* [ ] ZeroInflatedPoisson

**Comment by aleicazatti** [comment]
I'm working on the Student's T

**Comment by aleicazatti** [comment]
I will continue with the logistic distribution

**Comment by aleicazatti** [comment]
Working on Cauchy

**Comment by aleicazatti** [comment]
Working on lognormal

**Comment by aleicazatti** [comment]
Working on exponential

**Comment by aloctavodia** [comment]
Working on Poisson

**Comment by aleicazatti** [comment]
Working on continuous uniform

**Comment by aloctavodia** [comment]
working on AsymetricLaplace

**Comment by aleicazatti** [comment]
Working on ChiSquared

**Comment by aleicazatti** [comment]
working on Gamma

**Comment by aleicazatti** [comment]
Working on HalfCauchy

**Comment by aleicazatti** [comment]
Working on HalfNormal

**Comment by aleicazatti** [comment]
Working on HalfStudentT

**Comment by aleicazatti** [comment]
Working on InverseGamma

**Comment by aleicazatti** [comment]
Working on Kumaraswamy

**Comment by aleicazatti** [comment]
Working on Laplace

**Comment by aleicazatti** [comment]
Working on Log-Logistic

**Comment by aleicazatti** [comment]
Working on LogitNormal

**Comment by aleicazatti** [comment]
Working on Moyal

**Comment by aleicazatti** [comment]
Working on Pareto

**Comment by aleicazatti** [comment]
Working on Rice

**Comment by aleicazatti** [comment]
SkewStudentT

**Comment by aleicazatti** [comment]
Working on Triangular

**Comment by aleicazatti** [comment]
Working on TruncatedNormal

**Comment by aleicazatti** [comment]
Working on VonMises
