### ISSUE TITLE
Create AsymmetricLaplace distribution page

### ISSUE THREAD

**Issue by aleicazatti** [arviz-devs/preliz#449]
## **Description:** 

Create an individual page for the AsymmetricLaplace distribution. This page should include:

- A detailed explanation of the distribution.
- Key properties and parameters.
- Example usage and code snippets.
- Relevant mathematical formulas.
- Bayesian-focused stories, applications, explanations, or use cases.

## **Images and visuals:**

- Include a high-quality image of the distribution's probability density function (PDF) or cumulative distribution function (CDF).
- Use different parameter values to see their effects on the distribution.

## **Related distributions:**

- Add a "See also" section linking to related distributions, such as the Laplace distribution, guided by the relationships in the [ProbOnto diagram](https://upload.wikimedia.org/wikipedia/commons/a/af/ProbOnto2.5.jpg) and other relevant sources.

## **Simplification and accessibility:**

- Ensure the information is presented in a simplified and accessible manner for users.
- Use bullet points and headings to organize content clearly.
- Follow the overall style and structure used in other distribution pages for consistency.

## Reference:

- [Link to issue #448 for discussion and context](https://github.com/arviz-devs/preliz/issues/448)

**Comment by aloctavodia** [comment]
For the image, we can use the same parameters used in the docstring.

For the text, we could reword/adap this text from Wikipedia 

## Story
The asymmetric Laplace distribution (ALD) is a generalization of the Laplace distribution. Just as the Laplace distribution consists of two exponential distributions of equal scale back-to-back about x = m, the asymmetric Laplace consists of two exponential distributions of unequal scale back to back about x = m, adjusted to assure continuity and normalization. 

The difference of two variates exponentially distributed with different means and rate parameters will be distributed according to the ALD. When the two rate parameters are equal, the difference will be distributed according to the Laplace distribution.

## Common use in Bayesian statistics

The Asymmetric Laplace distribution is commonly used with an alternative parameterization for performing quantile regression in a Bayesian inference context. Under this approach, the $\kappa$ parameter describing asymmetry is replaced with a $q$ parameter indicating the quantile desired. Using this parameterization, the likelihood of the Asymmetric Laplace Distribution is equivalent to the loss function employed in quantile regression.

Maybe also the text in this section??? not sure
https://en.wikipedia.org/wiki/Asymmetric_Laplace_distribution#Applications

We should also add a link to Wikipedia (we should do this for every distribution, as the Wikipedia pages are usually very complete)
