### ISSUE TITLE
predictive_explorer with bambi model KeyError

### ISSUE THREAD

**Issue by andins** [arviz-devs/preliz#460]
**Describe the bug**
I just installed the package and tried the docs example for predictive_explorer with a bambi model. I get a KeyError: 'a_mu'.
![image](https://github.com/arviz-devs/preliz/assets/12953365/1470ce6e-7714-4798-b492-9c4b5256a1ff)

**To Reproduce**
The notebook to reproduce the error is just the code in the docs but I attach it anyway.
```
import preliz as pz
import numpy as np
import bambi as bmb
import pandas as pd

data = pd.DataFrame(
    {
        "y": np.random.normal(size=100),
        "x": np.random.normal(size=100),
    }
)
def a_bambi_model(a_mu, a_sigma):
    prior = {"Intercept": bmb.Prior("Normal", mu=a_mu, sigma=a_sigma)}
    a_model = bmb.Model("y ~ x", data, priors=prior)
    return a_model

pz.predictive_explorer(a_bambi_model)
```

**Additional context**
I'm using 
llvmlite-0.42.0 
numba-0.59.1 
preliz-0.7.0 
ipympl-0.9.4 
ipython-genutils-0.2.0 
nbclient-0.5.13

**Comment by aloctavodia** [comment]
The documentation is reflecting changes on the main branch not yet released. It should work if you install from main.

**Comment by aloctavodia** [comment]
A new version has been released. The example should work. Notice that the Bambi and PyMC features for `predictive_explorer` are very new and still under development. If you find bugs we would love to hear about them. Thanks

**Comment by andins** [comment]
thank you very much @aloctavodia !
Now it works. It still breaks with a multilevel model but I guess you already know and it's expected since it's under development.

**Comment by aloctavodia** [comment]
Hi @andins do you mean it fails with a multilevel Bambi's model?
