### ISSUE TITLE
Dependencies list for documentation incomplete

### ISSUE THREAD

**Issue by drsimonmartin** [arviz-devs/preliz#462]
Some of the  examples on this page: https://preliz.readthedocs.io/en/latest/examples/observed_space_examples.html fail when using the myBinder.org functionality. It appears to be because pymc and Bambi are not included in the requirements list for the page.

```
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 3
      1 import arviz as az
      2 import preliz as pz
----> 3 import pymc as pm
      4 import bambi as bmb
      5 import numpy as np

ModuleNotFoundError: No module named 'pymc'
``` 

Suggested fix: add the relevant versions of pymc and Bambi to the requirements list. I'm not sure what the minimum version numbers are for these so have not created a PR

**Comment by aloctavodia** [comment]
Hi @drsimonmartin thanks for reporting this issue. PyMC and Bambi are optional dependencies we should clarify that in the examples and allow optional imports
