### ISSUE TITLE
Manage optional import of PyMC and Bambi in the docs

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/preliz#464]
See #462, we should clarify that pymc and bambi are optional imports and user need to have those installed if they want to run some of the examples. 

Additionally, for predictive_explorer it will be nice to have 3 tabs, one for a "preliz model", one for  a PyMC model and one for the Bambi model, when rendering the docs it will be enough to run only the preliz-tab

**Comment by rohanbabbar04** [comment]
Sounds great...
I will pick this issue.

**Comment by rohanbabbar04** [comment]
In this can we do something like this in `observed_space_examples.ipynb`,

```
In [2]:  !{sys.executable} -m pip install pymc    # To support pymc
```

```
In [3]:  !{sys.executable} -m pip install bambi    # To support bambi
```

With some text why we install it, what do you think is this better than going for 3 tabs.

**Comment by aloctavodia** [comment]
Tabs provides a better layout and organization of the example. 

We are going to remove thebe (no more live docs), so no need for those import lines

A message saying that pymc or bambi are needed to run the Bambi and pymc examples should be enough. Additionally, if we want something  fancy we can do something similar to what is done in pymc examples 
https://www.pymc.io/projects/examples/en/latest/bart/bart_categorical_hawks.html
