### ISSUE TITLE
Cannot see moments label from plot_pdf, plot_cdf in Jupyter Notebook

### ISSUE THREAD

**Issue by random-walkie** [arviz-devs/preliz#470]
**Describe the bug**
Calling the moments label from plot_pdf, plot_cdf does not print it in the graph's legend, in Jupyter Notebook.

**To Reproduce**
You should be able to reproduce the bug from this commit: https://github.com/random-walkie/pymc_bayesian/commit/1cac891603dffd056aa09c3399875d66779ac3e1

- I am loading the docker container in VS Code and running the code in chapter1_exercises.ipynb.
- The error is seen on the last plot of exercise 7: https://github.com/random-walkie/pymc_bayesian/blob/main/chapter1_exercises.ipynb 
- I have tried changing the code to `dist.plot_pdf(moments=["m", "d"])` or `dist.plot_pdf(moments=["md"])`, with the same (non-)results.

**Expected behavior**
Expected labels for mean and standard deviation moments to be printed in the plot legend.

**Additional context**
Versions of `preliz` and other libraries used, operating system used, and anything else that may be useful: listed in requirements.txt and above.

**Comment by aloctavodia** [comment]
Thanks for reporting this issue it should be fixed soon. Once the associated PR is merged you can install PreliZ from GitHub (main branch) or wait until the next release.

**Comment by aloctavodia** [comment]
It should be fixed on preliz 0.8.1
