### ISSUE TITLE
Distribution gallery: alternative parametrization

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/preliz#493]
@tomicapretto suggested adding a plot showing alternative parametrizations for the distribution that has it. For instance, for the Beta we have (mu and nu) and (mu and sigma).

Not sure if we should only add the pdf or also the cdf. Also not sure if we should use the same shape as for the default parametrization, so same plot different labels. 

Alternatively, instead of a separated plot we could write some  text showing the equivalent, something like Beta(0.5, 0.5) is equivalent to Beta(mu=0.5, sigma=0.35) and Beta(mu=0.5, nu=1).

**Comment by aloctavodia** [comment]
@OriolAbril Can we have tabs with code-cells for this. The files are markdown, or do we need to write them in rst?

**Comment by OriolAbril** [comment]
Tabs can be done in myst or rst indiferently: https://sphinx-design.readthedocs.io/en/latest/tabs.html

**Comment by aloctavodia** [comment]
I think those are just tabs, not tabs with code. The idea is to allow the PDF plots so that the user can switch between parametrization (instead of showing one below the other). The same for the CDF plots

**Comment by OriolAbril** [comment]
Not sure what you mean by "tabs with code". If something like https://arviz-plots.readthedocs.io/en/latest/gallery/plot_forest_ess.html (there is code within the tabs to generate the plots) you can see their markdown source clicking on the navbar download icon then .md. If something else we can discuss it the next time we chat too

**Comment by aloctavodia** [comment]
Yes, that's exactly what I want, thanks!

**Comment by aloctavodia** [comment]
@aleicazatti can you give this a try?

**Comment by aleicazatti** [comment]
Yes, I will work on this!

**Comment by aleicazatti** [comment]
Hi, I've been trying to make it work for Beta, and I tried several things but the code is being displayed as plain text rather than being executed to show the plots.

Here’s an example of what I’ve tried:

```

::::::{tab-set}
   
:::::{tab-item} $\alpha$ and $\beta$
   
    ```{code-cell}
    ---
    tags: [remove-input]
    mystnb: image
    ---
    
    import matplotlib.pyplot as plt
    from preliz import Beta, style
    style.use('preliz-doc')
    alphas = [.5, 5., 2.]
    betas = [.5, 5., 5.]
    for alpha, beta in zip(alphas, betas):
        ax = Beta(alpha, beta).plot_pdf()
    ```

:::::

:::::{tab-item} $\mu$ and $\sigma$  

    ```{code-cell}
    ---
    tags: [remove-input]
    mystnb: image
    ---
    import matplotlib.pyplot as plt
    from preliz import Beta, style
    style.use('preliz-doc')
    mus = [.25, .5, .75]
    sigmas = [.1, .1, .1]
    for mu, sigma in zip(mus, sigmas):
        ax = Beta(mu, sigma, param='mean').plot_pdf()
    ```

:::::


:::::{tab-item} $\mu$ and $\kappa$

    ```{code-cell}
    ---
    tags: [remove-input]
    mystnb: image
    ---
    import matplotlib.pyplot as plt
    from preliz import Beta, style
    style.use('preliz-doc')
    mus = [.25, .5, .75]
    kappas = [2, 2, 2]
    for mu, kappa in zip(mus, kappas):
        ax = Beta(mu, kappa, param='mean').plot_pdf()
    ```

:::::

::::::
```

I've tried: 

* Using `{jupyter-execute}` instead of `{code-cell}` to attempt executing the code within the tabs.

* Tried :sync-group: and :sync: options but I don't know if they are necessary.

* Including `plt.show()` in the code blocks to force the plots to render.

**Comment by aloctavodia** [comment]
I will need to try this myself before providing an answer

**Comment by OriolAbril** [comment]
Anything that is indented 4 spaces in markdown is treated as code. That is:

````
    text here

```
text here
```
````

are equivalent. Remove the indentation and use `jupyter-execute` (`code-cell` is a bit wierd as a directive and doesn't allow nesting). I think `plt.show()` won't be needed, but it also won't hurt so either option should be fine

**Comment by OriolAbril** [comment]
> Tried :sync-group: and :sync: options but I don't know if they are necessary.

These are for configuring tab behaviour. In `arviz-plots` they are used to share the active tab across pages. If you go to an example, change tab, then use the sidebar to jump to a different example, the same tab/backend should be active. By using those we also customize the url that can be shared so a specific tab is active when opening:

* https://arviz-plots.readthedocs.io/en/latest//gallery/plot_forest_ess.html?backend=bokeh#synchronised-tabs opens with bokeh tab as active one
* https://arviz-plots.readthedocs.io/en/latest//gallery/plot_forest_ess.html?backend=plotly#synchronised-tabs opens with plotly tab as active

Docs: https://sphinx-design.readthedocs.io/en/latest/tabs.html#synchronised-tabs

**Comment by aleicazatti** [comment]
Hi, I tried these suggestions, but it's still not working. I also tried reinstalling packages and environments. In case I have a local problem, I think I could try opening a PR so you can take a look.
