### ISSUE TITLE
improve posterior_to_prior test

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/preliz#513]
A very basic test was introduced in #512, we should improve it. For instance, we should check that `pz.posterior_to_prior(model, idata, alternative={"b": [pz.Gamma(mu=0)]})` returns a Gamma distribution for parameter "b" with the mu, sigma parametrization while `pz.posterior_to_prior(model, idata, alternative="auto")` returns the same but with the alpha, and beta parametrization.

**Comment by aloctavodia** [comment]
@rohanbabbar04 Can you work on this?

**Comment by rohanbabbar04** [comment]
Sure I will work on this
