### ISSUE TITLE
API change maxent and quartile functions

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/preliz#517]
maxent and quartile both accept a distribution, modify it in place and by default plot the modified distribution.  They both return the axes and the optimization object from scipy.optimize. This is usually ok. But there are instances that a different behaviour will be more useful for instance a common pattern when working with GPs in PyMC is to do something like this 

```python
ell_t_params = pm.find_constrained_prior(
    pm.Lognormal, lower=0.5, upper=4.0, mass=0.95, init_guess={"mu": 1.0, "sigma": 1.0}
)
ell_t = pm.Lognormal("ell_t", **ell_t_params)
```
To do that with maxent we need to write something like 

```python
dist = pz.Lognormal()
pz.maxent(dist, 0.5, 4, 0.95, plot=False)
ell_t = pm.Lognormal("ell_t", **zip(dist.param_names, dist.params)
```

Those extra steps are annoying. We should have something that allows a single line, like this:

```python
ell_t_params = pz.maxent(pz.Lognormal(), 0.5, 4, 0.95, return_params=True)
ell_t = pm.Lognormal("ell_t", **ell_t_params)
```
This will disable the plot and change the output from (axes, opt-object) to dict

What do you think? What other alternatives could we implement?

**Comment by aloctavodia** [comment]
This is related to #518

**Comment by aloctavodia** [comment]
Maybe something even simpler is to get rid of the optimization object, it will not be useful for most users anyway, (or save it as an attribute and instead return a tuple with the axes and the a dict names:vals. So we should be able to do this

```python
_, ell_t_params = pz.maxent(pz.Lognormal(), 0.5, 4, 0.95, plot=False)
ell_t = pm.Lognormal("ell_t", **ell_t_params)
```

**Comment by bwengals** [comment]
My least favorite thing about
```python
ell_t_params = pm.find_constrained_prior(
    pm.Lognormal, lower=0.5, upper=4.0, mass=0.95, init_guess={"mu": 1.0, "sigma": 1.0}
)
ell_t = pm.Lognormal("ell_t", **ell_t_params)
```
is having to write `pm.Lognormal` twice.  

Would it be crazy to do something like
```python
ell_t = pz.maxent(pz.Lognormal, 0.5, 4, 0.95, pymc_kwargs={"name": "ell_t"})
```
and make it a one liner?

**Comment by bwengals** [comment]
I do also like what you had here
```python
_, ell_t_params = pz.maxent(pz.Lognormal(), 0.5, 4, 0.95, plot=False)
ell_t = pm.Lognormal("ell_t", **ell_t_params)
```

**Comment by aloctavodia** [comment]
Thanks for the input! This makes me think that we need a `.to_pymc()` method so we can do

```python
ell_t = pz.maxent(pz.Lognormal, 0.5, 4, 0.95).to_pymc("ell_t")
```
