### ISSUE TITLE
Export roulette state/figures to variables

### ISSUE THREAD

**Issue by peter-8640** [arviz-devs/preliz#545]
Say we have:
``` py
%matplotlib widget
pz.roulette()
```
![image](https://github.com/user-attachments/assets/504ac1e3-80f0-4ffd-a840-bc2e939fac6c)

Is it possible to get:
- histograms / chip stacks
- Suggested curve (here DiscreteWeibull, q=1.0, beta=3.92

Is this stored somewhere under the hood as a json? then it would be easy enough to parse downstream.

---

Hopefully this is is just a docs question, but if it isn't already possible then I guess this is a feature request.
Thanks!

**Comment by aloctavodia** [comment]
Hi @peter-8640, Now is not possible. But I have been thinking about adding this. Originally my idea was to provide easy access to the fitted distribution. But now I wonder if I should do the same with the "histogram/chips". Why do you think having access to the "histogram/chips" is a good idea? I am curious what do you want to do with that information?

**Comment by peter-8640** [comment]
Hi @aloctavodia 
My use case is to use jupyter as a form and gather multiple views around the distribution of the same event. Then save the form responses (somewhere else in the form there will be an identifier field, which I would link to the result). If there was a way to access this it could be trivially written to file or database.

Having histogram/chips stored would be interesting for combining multiple views.
Say, 
- x1, x2, x3... xn are n different sets of inputs from n people
- each produce a distribution f1, f2, f3 ... fn

We want a combined distribution, applying some creibility weighting h to each of them
I think it would be much better to use:
> h1 \*x1 + h2 \*x2 + h3\*x3 ... hn\*xn

Than
> h1 \*f1 + h2 \*f2 + h3\*f3 ... hn\*fn

To fit a combined distribution

**Comment by aloctavodia** [comment]
I created a function that combines the outputs of many Roulette instances. I tried different made-up examples and the result looked as expected. I will keep testing, most likely next week. Feel free to try it and give any suggestions if you have any. https://github.com/arviz-devs/preliz/pull/555
