### ISSUE TITLE
posterior_to_prior TypingError: Failed in nopython mode pipeline (step: nopython frontend)

### ISSUE THREAD

**Issue by dirknbr** [arviz-devs/preliz#564]
this instance gives an error in a colab

```
n = 100
X = np.random.normal(10, 1, (n, 2))
y = 10 + X.dot([1, 1.5]) + np.random.normal(0, 2, n)
with pm.Model() as model:
  a = pm.Normal('a', 5, 10)
  b = pm.Normal('b', [0, -10], 1)
  pred = pm.Normal('pred', a + pm.math.dot(X, b), 1, observed=y)
  trace = pm.sample()
preliz.posterior_to_prior(model, trace)
```

```
preliz.posterior_to_prior(model, trace)

3 frames

[/usr/local/lib/python3.10/dist-packages/preliz/ppls/agnostic.py](https://localhost:8080/#) in posterior_to_prior(model, idata, alternative, engine)
     49     if alternative is None:
     50         for var, dist in model_info.items():
---> 51             dist._fit_mle(posterior[var].values)
     52             new_priors[var] = dist
     53     else:

[/usr/local/lib/python3.10/dist-packages/preliz/distributions/normal.py](https://localhost:8080/#) in _fit_mle(self, sample)
    155 
    156     def _fit_mle(self, sample):
--> 157         self._update(*nb_fit_mle(sample))
    158 
    159 

[/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py](https://localhost:8080/#) in _compile_for_args(self, *args, **kws)
    421                 e.patch_message(msg)
    422 
--> 423             error_rewrite(e, 'typing')
    424         except errors.UnsupportedError as e:
    425             # Something unsupported is present in the user code, add help info

[/usr/local/lib/python3.10/dist-packages/numba/core/dispatcher.py](https://localhost:8080/#) in error_rewrite(e, issue_type)
    362                 raise e
    363             else:
--> 364                 raise e.with_traceback(None)
    365 
    366         argtypes = []

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function iadd>) found for signature:
 
 >>> iadd(Literal[int](0), array(float64, 1d, C))
 
There are 18 candidate implementations:
  - Of which 16 did not match due to:
  Overload of function 'iadd': File: <numerous>: Line N/A.
    With argument(s): '(int64, array(float64, 1d, C))':
   No match.
  - Of which 2 did not match due to:
  Operator Overload in function 'iadd': File: unknown: Line unknown.
    With argument(s): '(int64, array(float64, 1d, C))':
   No match for registered cases:
    * (int64, int64) -> int64
    * (int64, uint64) -> int64
    * (uint64, int64) -> int64
    * (uint64, uint64) -> uint64
    * (float32, float32) -> float32
    * (float64, float64) -> float64
    * (complex64, complex64) -> complex64
    * (complex128, complex128) -> complex128

During: typing of intrinsic-call at /usr/local/lib/python3.10/dist-packages/preliz/internal/special.py (547)

File "../usr/local/lib/python3.10/dist-packages/preliz/internal/special.py", line 547:
def mean_and_std(data):
    <source elided>
    for x in data:
        sum_sq_diff += (x - mean) ** 2
        ^

During: resolving callee type: type(CPUDispatcher(<function mean_and_std at 0x79e83d453760>))
During: typing of call at /usr/local/lib/python3.10/dist-packages/preliz/distributions/normal.py (183)

During: resolving callee type: type(CPUDispatcher(<function mean_and_std at 0x79e83d453760>))
During: typing of call at /usr/local/lib/python3.10/dist-packages/preliz/distributions/normal.py (183)


File "../usr/local/lib/python3.10/dist-packages/preliz/distributions/normal.py", line 183:
def nb_fit_mle(sample):
    return mean_and_std(sample)
    ^

```

**Comment by aloctavodia** [comment]
Thanks for reporting this will be fixed soon.

**Comment by dirknbr** [comment]
I still get the same error after this change

Can you add a unit test for this

**Comment by aloctavodia** [comment]
Did you update to the last version from github?

**Comment by dirknbr** [comment]
I ran a fresh colab which pip installed latest version

**Comment by aloctavodia** [comment]
Did you run `pip install git+git://github.com/arviz-devs/preliz.git`? The example not running is the same you shared at the beginning of this post? Is the error still the same?

**Comment by aloctavodia** [comment]
It runs for me and I get 

"This is an experimental method under development, use with caution.
with pm.Model() as model:
   a = pm.Normal("a", mu=13.3, sigma=1.51)
   b = pm.Normal("b", mu=[0.925, 1.28], sigma=[0.0997, 0.11], shape=2)

**Comment by dirknbr** [comment]
the code works now

but do you think this actually estimates the prior, it just seems to copy the posterior?

**Comment by aloctavodia** [comment]
Can you clarify what you expect this function to do? Or more general what do you would like this function (or other function) to do?

This function fits the posterior samples into the prior families using MLE (or alternatively into new families). You may want to use it if you are estimating posterior sequentially. i.e you have a dataset + model from which you compute a posterior, then you get a new dataset and you want to use the previously obtained posterior as prior for this new dataset. 

Using a posterior prior to the next analysis is not usually an easy task unless you have conjugate models or relatively simple posteriors. For instance `posterior_to_prior` fits the marginals, so correlations in the posterior between parameters will be lost. For many models, this will be a very bad approximation.

We exposed `posterior_to_prior` to users in case they find it useful in other ways we have not anticipated. But for us the main use of  `posterior_to_prior` is to serve other functions in PreliZ, like ppe, there not taking into account correlation between parameters is an ok approximation.

`ppe` is a function that attempts to estimate a prior, assuming the user has an idea about how the prior predictive distributions should look like. So it's turning what the user thinks the data may look like into a prior. `ppe` is also an experimental function with no guarantees at this point.

**Comment by dirknbr** [comment]
Thanks, yes I must have misinterpreted the function, I was expecting it to derive a prior given the posterior.

I was thinking along these lines 
https://academic.oup.com/ectj/article/27/1/151/7288648
