### ISSUE TITLE
Missing distributions

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/preliz#67]
All new distributions should include an alternative parametrization if useful/common. We should at least cover the parametrization in PyMC, but we can consider having others too (for example the beta has kappa parameter that is useful but not present in PyMC).

* [x] Uniform
* [x] Normal
* [x] TruncatedNormal
* [x] Beta
* [x] BetaScaled 
* [x] Kumaraswamy
* [x] Exponential (alternative parametrization)
* [x] Laplace
* [x] StudentT
* [x] Cauchy
* [x] HalfCauchy
* [x] Gamma
* [x] Weibull
* [x] HalfStudentT
* [x] LogNormal
* [x] ChiSquared
* [x] HalfNormal
* [x] Wald (alternative parametrization)
* [x] Pareto
* [x] InverseGamma
* [x] ExGaussian
* [x] VonMises
* [x] SkewNormal
* [x] Triangular
* [x] Gumbel
* [x] Logistic
* [x] LogitNormal
* [x] LogNormal
* [x] Rice
* [x] Moyal
* [x] AsymmetricLaplace
* [x] Binomial
* [x] BetaBinomial
* [x] Bernoulli
* [x] Poisson
* [x] NegativeBinomial
* [x] ZeroInflatedPoisson
* [x] ZeroInflatedBinomial
* [x] ZeroInflatedNegativeBinomial
* [x] DiscreteUniform
* [x] Geometric
* [x] HyperGeometric
* [x] Categorical
* [x] MvNormal (add alternative parametrization)

**Comment by aleicazatti** [comment]
This set of distributions is already implemented in PreliZ. To suggest new distributions, we can open an individual issue for each one.
