### ISSUE TITLE
ppa not showing in docs

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/preliz#9]
https://preliz.readthedocs.io/en/latest/api_reference.html#module-preliz

@OriolAbril do you know what am I missing?

**Comment by OriolAbril** [comment]
It has no docstring, by default autodoc lists only objects with a docstring. I would add a docstring, even if one line only,  but if you want everything to show up,  even things without docstring you need to use this https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#directive-option-automodule-undoc-members

**Comment by aloctavodia** [comment]
ohhh boy!  I swear I checked for the docstring and I say, yeah it has a docstring, haha.
